[package]
name = "otp"
description = "A simple command line HOTP and TOTP generator"
version = "0.1.0"
authors = ["acheronfail <acheronfail@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = "1.0"
data-encoding = "2.1.2"
err-derive = "0.2.1"
ring = "0.16.9"
clap = { version = "3.0.0-beta.2" }
anyhow = "1.0.34"
